CREATE SCHEMA IF NOT EXISTS vaultbase;

CREATE TABLE IF NOT EXISTS vaultbase.schema_migrations (
  version text PRIMARY KEY,
  applied_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS vaultbase.projects (
  id text PRIMARY KEY,
  project_ref text NOT NULL UNIQUE,
  display_name text NOT NULL,
  region text,
  plan text NOT NULL CHECK (plan IN ('free', 'pro', 'team', 'enterprise')),
  enabled boolean NOT NULL DEFAULT true,
  backup_schedule text NOT NULL DEFAULT '0 3 * * *',
  keep_alive_schedule text,
  backup_mode text NOT NULL DEFAULT 'database' CHECK (backup_mode IN ('database', 'full_project')),
  secret_ref text NOT NULL UNIQUE,
  last_backup_at timestamptz,
  measured_dump_bytes bigint NOT NULL DEFAULT 0 CHECK (measured_dump_bytes >= 0),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'healthy', 'warning', 'failed', 'paused', 'disabled')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS vaultbase.snapshots (
  id uuid PRIMARY KEY,
  project_id text NOT NULL REFERENCES vaultbase.projects(id) ON DELETE CASCADE,
  restic_snapshot_id text UNIQUE,
  status text NOT NULL CHECK (status IN ('running', 'uploaded', 'verified', 'restore_verified', 'failed')),
  components jsonb NOT NULL DEFAULT '{}'::jsonb,
  dump_bytes bigint NOT NULL DEFAULT 0 CHECK (dump_bytes >= 0),
  started_at timestamptz NOT NULL,
  completed_at timestamptz,
  verified_at timestamptz,
  expires_at timestamptz,
  error_code text,
  error_summary text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS snapshots_project_started_idx ON vaultbase.snapshots(project_id, started_at DESC);

CREATE TABLE IF NOT EXISTS vaultbase.activities (
  id uuid PRIMARY KEY,
  project_id text REFERENCES vaultbase.projects(id) ON DELETE SET NULL,
  snapshot_id uuid REFERENCES vaultbase.snapshots(id) ON DELETE SET NULL,
  event_type text NOT NULL,
  status text NOT NULL CHECK (status IN ('success', 'warning', 'failed')),
  message text NOT NULL,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  duration_ms integer CHECK (duration_ms >= 0),
  bytes bigint CHECK (bytes >= 0),
  occurred_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS activities_occurred_idx ON vaultbase.activities(occurred_at DESC);

CREATE TABLE IF NOT EXISTS vaultbase.audit_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor text NOT NULL,
  action text NOT NULL,
  target_type text NOT NULL,
  target_id text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS vaultbase.settings (
  key text PRIMARY KEY,
  value jsonb NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS vaultbase.mirror_runs (
  id uuid PRIMARY KEY,
  status text NOT NULL CHECK (status IN ('running', 'success', 'failed')),
  row_counts jsonb NOT NULL DEFAULT '{}'::jsonb,
  started_at timestamptz NOT NULL,
  completed_at timestamptz,
  error_summary text
);

INSERT INTO vaultbase.settings(key, value)
VALUES
  ('retention', '{"hourly":24,"daily":7,"weekly":4,"monthly":12}'::jsonb),
  ('mirror', '{"frequency":"daily","authoritative":"local_postgres","contains_secrets":false}'::jsonb)
ON CONFLICT (key) DO NOTHING;
